[package]
name = "youtube_to_soundcloud"
version = "0.1.0"
authors = ["e00E <vakevk@gmail.com>"]

[dependencies]
reqwest = "0.6"
serde = "1"
serde_derive = "1"
serde_json = "1"
cpython = "0.1"
backoff = "0.1"
chrono = "0.4"