[package]
edition = "2018"
name = "youtube_to_soundcloud"
version = "0.1.0"

[dependencies]
backoff = "0.2"
chrono = "0.4"
reqwest = { version = "0.10", features = ["blocking", "json"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
url = "2.0"
